### PR TITLE
Allow range of Toil versions (resolves #25)

### LINKED ISSUE #25: Setup only allows old version of Toil
Setup.py only allows 3.3.1. There should be a range of versions allowed like in toil-scripts. I found this by trying to run the provisioner integrations tests based on toil-script RNASeq with Toil master (3.5.0). Pip installing toil-scripts causes toil-lib to be installed, which then installs Toil==3.3.1 and then uninstalls my version.

### PR DESCRIPTION
**Pull request by cket**

### CODE REVIEW

**Comment by cket** [comment]
@hannes-ucsc @jvivian can you take a look at this?

**Comment by jvivian** [comment]
I'd prefer pinning a specific version of Toil, but since toil-scripts currently supports a range it doesn't really make sense for toil-lib not to. Thanks for filing a PR, looking at it now.

**Comment by jvivian** [comment]
+1 — Code is copied from toil-scripts which @hannes-ucsc wrote.

**Comment by jvivian** [comment]
Ah, I missed the necessary change to `jenkins.sh` you'd need once you removed Toil from `setup.py`.

**Pull request merged**
