### PR TITLE
Move toil.spark to toil_lib.spark (resolves #45)

### LINKED ISSUE #45: Move Spark service jobs over from toil
https://github.com/BD2KGenomics/toil/issues/1178

### PR DESCRIPTION
**Pull request by fnothaft**
CC @arkal @almussel

### CODE REVIEW

**Comment by arkal** [comment]
@fnothaft are you going to make the appropriate docker call invocations?

**Comment by arkal** [comment]
You will need to import `docker_call`

**Comment by fnothaft** [comment]
Hi @arkal I'm running into some issues getting the tests passing. I'm not sure if this is because I'm running on an old Toil (I believe I've got the latest `3.5.0a1.dev247` installed in my venv) or if there's a problem using the `docker_call` defer functionality with service jobs. I've just pushed my latest changes, so we'll see if the tests still fail.

I'm planning to be at UCSC tomorrow (CC @hannes-ucsc @almussel @jvivian for a heads up; forgot to say that on scrum today), so if this issue reproduces on Jenkins, we can look at this together.

**Comment by arkal** [comment]
Sounds good!

**Comment by fnothaft** [comment]
Just fixed conflicts, but this still depends on https://github.com/BD2KGenomics/toil/issues/1191 upstream (cc @almussel for FYI)

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
This interacts weirdly with other PR since currently no master branch of any project contains the code that is added by this PR.  We have a workaround

https://github.com/BD2KGenomics/toil-scripts/pull/475#discussion_r85007058

@fnothaft, is the test failure 1) expected and 2) deterministic?

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by fnothaft** [comment]
@hannes-ucsc can you take a look at Jenkins. I'm seeing:

```
E             File "/mnt/ephemeral/workspace/toil-lib/.env/local/lib/python2.7/site-packages/toil/job.py", line 1388, in _run
E               returnValues = self.run(fileStore)
E             File "/mnt/ephemeral/workspace/toil-lib/.env/local/lib/python2.7/site-packages/toil/job.py", line 1335, in run
E               startCredentials = service.start(fileStore)
E             File "/mnt/ephemeral/workspace/toil-lib/src/toil_lib/spark.py", line 148, in start
E               check_output = True)[:-1]
E             File "/mnt/ephemeral/workspace/toil-lib/src/toil_lib/programs.py", line 107, in docker_call
E               container_name = _get_container_name(job)
E             File "/mnt/ephemeral/workspace/toil-lib/src/toil_lib/programs.py", line 219, in _get_container_name
E               return '--'.join([job.fileStore.jobStore.config.workflowID,
E           AttributeError: 'FileStore' object has no attribute 'fileStore'
E           Exiting the worker because of a failed jobWrapper on host ip-172-31-24-117
E           ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host ip-172-31-24-117
E           WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job U/x/jobFOiuLr to 0
```

After https://github.com/BD2KGenomics/toil/pull/1198, the `FileStore` argument that we're getting should be a `ServiceJob`. Can you look into why we're not getting this?

**Comment by hannes-ucsc** [comment]
@fnothaft, I think you just need to change `make prepare` to install toil-3.5.0a1.dev259 which I believe was the first master build that contained the changes from BD2KGenomics/toil#1198.

**Pull request merged**
